-- tables
-- Table: currency
CREATE TABLE currency
(
    code char(3)     NOT NULL,
    name varchar(64) NOT NULL,
    CONSTRAINT currency_pk PRIMARY KEY (code)
);

-- Table: product
CREATE TABLE product
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    sku           varchar(40)                                            NOT NULL,
    name          varchar(200)                                           NOT NULL,
    price_cents   int                                                    NOT NULL,
    currency_code char(3)                                                NOT NULL,
    created_at    timestamp DEFAULT CURRENT_TIMESTAMP                    NOT NULL,
    updated_at    timestamp DEFAULT CURRENT_TIMESTAMP                    NOT NULL,
    CONSTRAINT uk_product_sku UNIQUE (sku),
    CONSTRAINT chk_price_nonneg CHECK (price_cents >= 0),
    CONSTRAINT chk_currency_upper CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT chk_currency_len CHECK (CHAR_LENGTH(currency_code) = 3),
    CONSTRAINT product_pk PRIMARY KEY (id)
);

CREATE INDEX ix_product_created_at ON product (created_at);

-- Table: stock_movement
CREATE TABLE stock_movement
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    product_id      bigint                                                 NOT NULL,
    quantity_change int                                                    NOT NULL,
    reason          varchar(10)                                            NOT NULL,
    reference       varchar(100) NULL,
    created_at      timestamp DEFAULT CURRENT_TIMESTAMP                    NOT NULL,
    CONSTRAINT ck_stock_movement_reason CHECK (reason IN ('IN', 'OUT')),
    CONSTRAINT ck_stock_movement_nonzero_qty CHECK (quantity_change <> 0),
    CONSTRAINT ck_stock_movement_sign CHECK ((reason = 'IN' AND quantity_change > 0) OR
                                             (reason = 'OUT' AND quantity_change < 0)),
    CONSTRAINT stock_movement_pk PRIMARY KEY (id)
);

CREATE INDEX ix_stock_movement_product ON stock_movement (product_id);

CREATE INDEX ix_stock_movement_created_at ON stock_movement (created_at);

-- Table: category
CREATE TABLE category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    code       VARCHAR(50)                                            NOT NULL,
    name       VARCHAR(200)                                           NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                    NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                    NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uk_category_code UNIQUE (code)
);

-- Table: product_category
CREATE TABLE product_category
(
    product_id  BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    CONSTRAINT pk_product_category PRIMARY KEY (product_id, category_id),
    CONSTRAINT fk_product_category_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_product_category_category FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX ix_product_category_category ON product_category (category_id);

-- Table: warehouse
CREATE TABLE warehouse
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    code       VARCHAR(50)                                            NOT NULL,
    name       VARCHAR(200)                                           NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                    NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP                    NOT NULL,
    CONSTRAINT pk_warehouse PRIMARY KEY (id),
    CONSTRAINT uk_warehouse_code UNIQUE (code)
);

-- Table: location
CREATE TABLE location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    warehouse_id BIGINT NOT NULL,
    code VARCHAR(50) NOT NULL,
    type VARCHAR(20) NOT NULL,
    is_pickable BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (id),
    CONSTRAINT fk_location_warehouse FOREIGN KEY (warehouse_id) REFERENCES warehouse(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT uk_location_wh_code UNIQUE (warehouse_id, code),
    CONSTRAINT chk_location_type CHECK (type IN ('BIN','STAGING','DAMAGED','RETURN','OTHER'))
);
CREATE INDEX ix_location_warehouse ON location(warehouse_id);

-- Table: stock_level
CREATE TABLE stock_level
(
    product_id   BIGINT                              NOT NULL,
    location_id BIGINT                               NOT NULL,
    quantity     INT                                 NOT NULL,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_stock_level PRIMARY KEY (product_id, location_id),
    CONSTRAINT fk_stock_level_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_stock_level_location FOREIGN KEY (location_id) REFERENCES location(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_stock_level_nonneg CHECK (quantity >= 0)
);
CREATE INDEX ix_stock_level_location ON stock_level (location_id);

-- Table: app_user
CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          password_hash VARCHAR(255) NOT NULL,
                          display_name VARCHAR(100),
                          is_active BOOLEAN DEFAULT TRUE NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CONSTRAINT pk_app_user PRIMARY KEY (id),
                          CONSTRAINT uk_app_user_email UNIQUE (email)
);

-- Table: app_role
CREATE TABLE app_role (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
                          code VARCHAR(50) NOT NULL,
                          name VARCHAR(100) NOT NULL,
                          CONSTRAINT pk_app_role PRIMARY KEY (id),
                          CONSTRAINT uk_app_role_code UNIQUE (code)
);

-- Table: app_user_role
CREATE TABLE app_user_role (
                               user_id BIGINT NOT NULL,
                               role_id BIGINT NOT NULL,
                               CONSTRAINT pk_app_user_role PRIMARY KEY (user_id, role_id),
                               CONSTRAINT fk_aur_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE ON UPDATE RESTRICT,
                               CONSTRAINT fk_aur_role FOREIGN KEY (role_id) REFERENCES app_role(id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX ix_aur_role ON app_user_role(role_id);

-- foreign keys
-- Reference: fk_product_currency (table: product)
ALTER TABLE product
    ADD CONSTRAINT fk_product_currency
        FOREIGN KEY (currency_code)
            REFERENCES currency (code)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;

-- Reference: stock_movement_product (table: stock_movement)
ALTER TABLE stock_movement
    ADD CONSTRAINT stock_movement_product
        FOREIGN KEY (product_id)
            REFERENCES product (id)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;

-- Stock_movement audit/raportite jaoks
-- NB: olemasoleva data säilitamiseks on veerud NULLABLE.

ALTER TABLE stock_movement ADD COLUMN location_id BIGINT NULL;

ALTER TABLE stock_movement ADD COLUMN reason_detail VARCHAR(20) NULL;

ALTER TABLE stock_movement ADD COLUMN correlation_id CHAR(36) NULL; -- nt UUID string

ALTER TABLE stock_movement ADD COLUMN performed_by BIGINT NULL;     -- kes tegi liikumise (app_user.id)

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_location
        FOREIGN KEY (location_id) REFERENCES location(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE stock_movement
    ADD CONSTRAINT fk_stock_movement_performed_by
        FOREIGN KEY (performed_by) REFERENCES app_user(id)
        ON DELETE SET NULL ON UPDATE RESTRICT;

CREATE INDEX ix_stock_movement_location ON stock_movement (location_id);
CREATE INDEX ix_stock_movement_performed_by ON stock_movement (performed_by);

-- Reason_detail lubatud väärtused (hoiab standardi paigas)
ALTER TABLE stock_movement
    ADD CONSTRAINT ck_stock_movement_reason_detail
    CHECK (reason_detail IS NULL OR reason_detail IN ('PURCHASE','SALE','RETURN_IN','RETURN_OUT','ADJUST','TRANSFER'));