-- tables
-- Table: currency
CREATE TABLE currency
(
    code char(3)     NOT NULL,
    name varchar(64) NOT NULL,
    CONSTRAINT currency_pk PRIMARY KEY (code)
);

-- Table: product
CREATE TABLE product
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    sku           varchar(40)                             NOT NULL,
    name          varchar(200)                            NOT NULL,
    price_cents   int                                     NOT NULL,
    currency_code char(3)                                 NOT NULL,
    created_at    timestamp DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    updated_at    timestamp DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    CONSTRAINT uk_product_sku UNIQUE (sku),
    CONSTRAINT chk_price_nonneg CHECK (price_cents >= 0),
    CONSTRAINT chk_currency_upper CHECK (currency_code = UPPER(currency_code)),
    CONSTRAINT chk_currency_len CHECK (CHAR_LENGTH(currency_code) = 3),
    CONSTRAINT product_pk PRIMARY KEY (id)
);

CREATE INDEX ix_product_created_at ON product (created_at);

-- Table: stock_movement
CREATE TABLE stock_movement
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    product_id      bigint                                  NOT NULL,
    quantity_change int                                     NOT NULL,
    reason          varchar(10)                             NOT NULL,
    reference       varchar(100) NULL,
    created_at      timestamp DEFAULT CURRENT_TIMESTAMP     NOT NULL,
    CONSTRAINT ck_stock_movement_reason CHECK (reason IN ('IN', 'OUT')),
    CONSTRAINT ck_stock_movement_nonzero_qty CHECK (quantity_change <> 0),
    CONSTRAINT ck_stock_movement_sign CHECK ((reason = 'IN' AND quantity_change > 0) OR
                                             (reason = 'OUT' AND quantity_change < 0)),
    CONSTRAINT stock_movement_pk PRIMARY KEY (id)
);

CREATE INDEX ix_stock_movement_product ON stock_movement (product_id);

CREATE INDEX ix_stock_movement_created_at ON stock_movement (created_at);

-- foreign keys
-- Reference: fk_product_currency (table: product)
ALTER TABLE product
    ADD CONSTRAINT fk_product_currency
        FOREIGN KEY (currency_code)
            REFERENCES currency (code)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;

-- Reference: stock_movement_product (table: stock_movement)
ALTER TABLE stock_movement
    ADD CONSTRAINT stock_movement_product
        FOREIGN KEY (product_id)
            REFERENCES product (id)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;